# fly.toml app configuration file generated for vat-validator on 2023-05-17T16:14:05+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "vat-validator"
primary_region = "ams"

[env]
  PORT = "8081"
  HOST = "https://vat-validator.fly.dev/"
  SHOPIFY_API_KEY = "25dd90b60e6506dcb9c5aedf271f1422"
  SCOPES = "write_products"

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
